[project]
name = "mvp-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mido>=1.3.3",
    "numpy>=2.2.6",
    "pygame>=2.6.1",
    "python-rtmidi>=1.5.8",
    "sounddevice>=0.5.2",
]
